version: "3.7"

services:
  postgres:
    image: postgres:10
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=R00Tpostgres
      - POSTGRES_DB=test-backend
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: "redis:5.0-alpine"
    ports:
      - "6379:6379"
    command: redis-server --maxclients 10000 --requirepass redis-test-ymb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres

volumes:
  pgdata:
